# Generated by Django 4.2 on 2023-06-19 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_venta_estado_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 19, 22, 16, 5, 321325, tzinfo=datetime.timezone.utc)),
        ),
    ]
