# Generated by Django 4.2.1 on 2023-07-04 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_detalleventa_remove_venta_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(default='EN PREPARACION', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 21, 0, 14, 711699)),
        ),
    ]
